CREATE TABLE [dbo].[CHAMPIONNAT_CONSTRUCTEURS]
(
	[Id] INT NOT NULL PRIMARY KEY identity(1,1),
	Id_Constructeur int,
	Points int, 
    CONSTRAINT [FK_CHAMPIONNAT_CONSTRUCTEURS_CONSTRUCTEURS] FOREIGN KEY (Id_Constructeur) REFERENCES CONSTRUCTEURS(Id),
)
