CREATE TABLE [dbo].[CHAMPIONAT_PILOTES]
(
	[Id] INT NOT NULL PRIMARY KEY identity(1,1),
	Id_Driver int,
	Points int, 
    CONSTRAINT [FK_CHAMPIONAT_PILOTES_DRIVERS] FOREIGN KEY (Id_Driver) REFERENCES DRIVERS(Id),
)
